### ISSUE TITLE
Cannot perform any authorization-required action

### ISSUE THREAD

**Issue by Kouassi-Goli** [adhavpavan/BasicNetwork-2.0#5]
When using the Node.Js API, one cannot for example execute Query Car By ID as it requires authorization. 
So we get instead a timeout form the server.
The problem is that when generating crypto materials, the connection profile `connection-org*.json` are not updated in the corresponding api folder (`api-2.0/config/`). 
One can use the `cpp-generate.sh` script provided in the test-network along with the corresponding `cpp-template` file to address the issue.

Server Logs
```
Wallet path: /home/TEST/BasicNetwork-2.0-master/api-2.0/org1-wallet
An identity for the admin user "admin" does not exist in the wallet
calling enroll Admin method
Wallet path: /home/TEST/BasicNetwork-2.0-master/api-2.0/org1-wallet
Successfully enrolled admin user "admin" and imported it into the wallet
Admin Enrolled Successfully
Successfully registered and enrolled admin user Kouassi and imported it into the wallet
chaincode name is :fabcar
args========== ["CAR0"]
Wallet path: /home/TEST/BasicNetwork-2.0-master/api-2.0/org1-wallet
2020-07-07T08:29:14.896Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
2020-07-07T08:29:14.898Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://localhost:7051 timeout:3000
2020-07-07T08:29:14.902Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer0.org1.example.com due to Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
    at checkState (/home/TEST/BasicNetwork-2.0-master/api-2.0/node_modules/@grpc/grpc-js/build/src/client.js:69:26)
    at Timeout._onTimeout (/home/TEST/BasicNetwork-2.0-master/api-2.0/node_modules/@grpc/grpc-js/build/src/channel.js:292:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  connectFailed: true
}
2020-07-07T08:29:17.908Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer1.org1.example.com, url:grpcs://localhost:8051, connected:false, connectAttempted:true
2020-07-07T08:29:17.908Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer1.org1.example.com url:grpcs://localhost:8051 timeout:3000
2020-07-07T08:29:17.909Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer1.org1.example.com due to Error: Failed to connect before the deadline on Endorser- name: peer1.org1.example.com, url:grpcs://localhost:8051, connected:false, connectAttempted:true
    at checkState (/home/TEST/BasicNetwork-2.0-master/api-2.0/node_modules/@grpc/grpc-js/build/src/client.js:69:26)
    at Timeout._onTimeout (/home/TEST/BasicNetwork-2.0-master/api-2.0/node_modules/@grpc/grpc-js/build/src/channel.js:292:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  connectFailed: true
}
2020-07-07T08:29:20.915Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Discoverer- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
2020-07-07T08:29:20.916Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://localhost:7051 timeout:3000
Failed to evaluate transaction: Error: Failed to connect before the deadline on Discoverer- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
```

**Comment by adhavpavan** [comment]
Thank you.

I will add this script when we create new cryptomaterials.

**Comment by adhavpavan** [comment]
Added script of generating connection profile for both orgs
